CREATE TABLE users(
	email CHAR(30) NOT NULL,
	password CHAR(64) NOT NULL,
	radiologia INT DEFAULT 0,
	mamografia INT DEFAULT 0,
	tomografia INT DEFAULT 0,
	radiologia_dental INT DEFAULT 0,
	PRIMARY KEY(email)
);
/*nserial -> serial*/
CREATE TABLE radiologia(
	email CHAR(30) NOT NULL,
	pais CHAR(15),
	nombre_inst CHAR(30),
	tipo_inst CHAR(1),
	marca CHAR(15),
	modelo CHAR(15),
	nserial CHAR(12),
	fecha_tubo DATE,
	sala CHAR(10),
	tipo_equipo CHAR(1),
	revelado CHAR(1),
	marca_revelado CHAR(15),
	modelo_revelado CHAR(15),
	pacientes_atendidos INT,
	sexo CHAR(1),
	peso INT,
	altura INT,
	edad INT,
	fecha_adquisicion_de_data DATE,
	tipo_estudio CHAR(25),
	kv CHAR(3),
	ma CHAR(3),
	t CHAR(4),
	mas CHAR(4),
	dosis CHAR(6),
	nombre_apellido_tec CHAR(20),
	turno CHAR(1)
);
/*revelado -> {húmedo , digitalizado CR , digital DR}*/
CREATE TABLE mamografia(
	email CHAR(30) NOT NULL,
	pais CHAR(15),
	nombre_inst CHAR(30),
	tipo_inst CHAR(1),
	marca CHAR(15),
	modelo CHAR(15),
	nserial CHAR(12),
	fecha_tubo DATE,
	sala CHAR(10),
	tipo_equipo CHAR(1),
	revelado CHAR(1),
	marca_revelado CHAR(15),
	modelo_revelado CHAR(15),
	pacientes_atendidos INT,
	sexo CHAR(1),
	peso INT,
	altura INT,
	talla_brasier CHAR(3),
	edad INT,
	fecha_adquisicion_de_data DATE,
	tipo_estudio CHAR(1),
	campo CHAR(9),
	cae CHAR(1),
	anodo_filtro CHAR(8),

	cc_d_dist_compresion INT,
	cc_d_fuerza_compresion INT,
	cc_d_kv CHAR(3),
	cc_d_ma  CHAR(3),
	cc_d_t  CHAR(4),
	cc_d_mas  CHAR(4),
	cc_d_dosis  CHAR(5),

	cc_i_dist_compresion INT,
	cc_i_fuerza_compresion INT,
	cc_i_kv CHAR(3),
	cc_i_ma  CHAR(3),
	cc_i_t  CHAR(4),
	cc_i_mas  CHAR(4),
	cc_i_dosis  CHAR(5),

	mlo_d_dist_compresion INT,
	mlo_d_fuerza_compresion INT,
	mlo_d_kv CHAR(3),
	mlo_d_ma  CHAR(3),
	mlo_d_t  CHAR(4),
	mlo_d_mas  CHAR(4),
	mlo_d_dosis  CHAR(5),

	mlo_i_dist_compresion INT,
	mlo_i_fuerza_compresion INT,
	mlo_i_kv CHAR(3),
	mlo_i_ma  CHAR(3),
	mlo_i_t  CHAR(4),
	mlo_i_mas  CHAR(4),
	mlo_i_dosis  CHAR(5),

	densidad_mama CHAR(1),/*FIBROGLANDULAR ADIPOSO O PROMEDIO*/

	nombre_apellido_tec CHAR(20),
	turno CHAR(1)
);
CREATE TABLE tomografia(
	email CHAR(30) NOT NULL,
	pais CHAR(15),
	nombre_inst CHAR(30),
	tipo_inst CHAR(1),
	marca CHAR(15),
	modelo CHAR(15),
	nserial CHAR(12),
	fecha_tubo DATE,
	sala CHAR(10),
	n_cortes INT,
	pacientes_atendidos INT,
	sexo CHAR(1),
	peso INT,
	altura INT,
	edad INT,
	fecha_adquisicion_de_data DATE,
	kv CHAR(3),
	ma CHAR(3),
	s CHAR(4),
	mas CHAR(4),
	longitud_exploracion CHAR(4),
	pitch CHAR(3),
	ctdi_vol CHAR(5),
	dlp CHAR(5),
	dlp_total CHAR(5),
	dosis CHAR(5),
	nombre_apellido_tec CHAR(20),
	turno CHAR(1)
);
CREATE TABLE radiologia_dental(
	email CHAR(30) NOT NULL,
	pais CHAR(15),
	nombre_inst CHAR(30),
	tipo_inst CHAR(1),
	marca CHAR(15),
	modelo CHAR(15),
	nserial CHAR(12),
	fecha_tubo DATE,
	sala CHAR(10),
	tipo_equipo CHAR(1),
	revelado CHAR(1),
	marca_revelado CHAR(15),
	modelo_revelado CHAR(15),
	pacientes_atendidos INT,
	sexo CHAR(1),
	peso INT,
	altura INT,
	edad INT,
	fecha_adquisicion_de_data DATE,
	posicion_paciente CHAR(1),
	kv CHAR(3),
	ma CHAR(3),
	t CHAR(4),
	mas CHAR(4),
	dosis CHAR(6),
	nombre_apellido_tec CHAR(20),
	turno CHAR(1)
);